# Column Mapping: Excel Column Name -> DocType Field Name

HEADER_MAPPING = {
    "NOMOR AJU": "nomoraju",
    "KODE DOKUMEN": "kode_dokumen",
    "KODE KANTOR": "kode_kantor",
    "KODE KANTOR BONGKAR": "kode_kantor_bongkar",
    "KODE KANTOR PERIKSA": "kode_kantor_periksa",
    "KODE KANTOR TUJUAN": "kode_kantor_tujuan",
    "KODE KANTOR EKSPOR": "kode_kantor_ekspor",
    "KODE JENIS IMPOR": "kode_jenis_impor",
    "KODE JENIS EKSPOR": "kode_jenis_ekspor",
    "KODE JENIS TPB": "kode_jenis_tpb",
    "KODE JENIS PLB": "kode_jenis_plb",
    "KODE JENIS PROSEDUR": "kode_jenis_pib",
    "KODE TUJUAN PEMASUKAN": "kode_tujuan_pemasukan",
    "KODE TUJUAN PENGIRIMAN": "kode_tujuan_pengiriman",
    "KODE TUJUAN TPB": "kode_tujuan_tpb",
    "KODE CARA DAGANG": "kode_cara_dagang",
    "KODE CARA BAYAR": "kode_cara_bayar",
    "KODE CARA BAYAR LAINNYA": "kode_cara_bayar_lainnya",
    "KODE GUDANG ASAL": "kode_gudang_asal",
    "KODE GUDANG TUJUAN": "kode_gudang_tujuan",
    "KODE JENIS KIRIM": "kode_jenis_kirim",
    "KODE JENIS PENGIRIMAN": "kode_jenis_pengiriman",
    "KODE KATEGORI EKSPOR": "kode_kategori_ekspor",
    "KODE KATEGORI MASUK FTZ": "kode_kategori_masuk_ftz",
    "KODE KATEGORI KELUAR FTZ": "kode_kategori_keluar_ftz",
    "KODE KATEGORI BARANG FTZ": "kode_kategori_barang_ftz",
    "KODE LOKASI": "kode_lokasi",
    "KODE LOKASI BAYAR": "kode_lokasi_bayar",
    "LOKASI ASAL": "lokasi_asal",
    "LOKASI TUJUAN": "lokasi_tujuan",
    "KODE DAERAH ASAL": "kode_daerah_asal",
    "KODE NEGARA TUJUAN": "kode_negara_tujuan",
    "KODE TUTUP PU": "kode_tutup_pu",
    "NOMOR BC11": "nomor_bc11",
    "TANGGAL BC11": "tanggal_bc11",
    "NOMOR POS": "nomor_pos",
    "NOMOR SUB POS": "nomor_sub_pos",
    "KODE PELABUHAN BONGKAR": "kode_pelabuhan_bongkar",
    "KODE PELABUHAN MUAT": "kode_pelabuhan_muat",
    "KODE PELABUHAN MUAT AKHIR": "kode_pelabuhan_muat_akhir",
    "KODE PELABUHAN TRANSIT": "kode_pelabuhan_transit",
    "KODE PELABUHAN TUJUAN": "kode_pelabuhan_tujuan",
    "KODE PELABUHAN EKSPOR": "kode_pelabuhan_ekspor",
    "KODE TPS": "kode_tps",
    "TANGGAL BERANGKAT": "tanggal_berangkat",
    "TANGGAL EKSPOR": "tanggal_ekspor",
    "TANGGAL MASUK": "tanggal_masuk",
    "TANGGAL MUAT": "tanggal_muat",
    "TANGGAL TIBA": "tanggal_tiba",
    "TANGGAL PERIKSA": "tanggal_periksa",
    "TEMPAT STUFFING": "tempat_stuffing",
    "TANGGAL STUFFING": "tanggal_stuffing",
    "KODE TANDA PENGAMAN": "kode_tanda_pengaman",
    "JUMLAH TANDA PENGAMAN": "jumlah_tanda_pengaman",
    "FLAG CURAH": "flag_curah",
    "FLAG SDA": "flag_sda",
    "FLAG VD": "flag_vd",
    "FLAG MIGAS": "flag_migas",
    "KODE ASURANSI": "kode_asuransi",
    "ASURANSI": "asuransi",
    "NILAI BARANG": "nilai_barang",
    "NILAI INCOTERM": "nilai_incoterm",
    "NILAI MAKLON": "nilai_maklon",
    "FREIGHT": "freight",
    "FOB": "fob",
    "BIAYA TAMBAHAN": "biaya_tambahan",
    "BIAYA PENGURANG": "biaya_pengurang",
    "VD": "vd",
    "CIF": "cif",
    "HARGA_PENYERAHAN": "harga_penyerahan",
    "NDPBM": "ndpbm",
    "TOTAL DANA SAWIT": "total_dana_sawit",
    "DASAR PENGENAAN PAJAK": "dasar_pengenaan_pajak",
    "NILAI JASA": "nilai_jasa",
    "UANG MUKA": "uang_muka",
    "BRUTO": "bruto",
    "NETTO": "netto",
    "VOLUME": "volume",
    "KOTA PERNYATAAN": "kota_pernyataan",
    "TANGGAL PERNYATAAN": "tanggal_pernyataan",
    "NAMA PERNYATAAN": "nama_pernyataan",
    "JABATAN PERNYATAAN": "jabatan_pernyataan",
    "KODE VALUTA": "kode_valuta",
    "KODE INCOTERM": "kode_incoterm",
    "KODE JASA KENA PAJAK": "kode_jasa_kena_pajak",
    "NOMOR BUKTI BAYAR": "nomor_bukti_bayar",
    "TANGGAL BUKTI BAYAR": "tanggal_bukti_bayar",
    "KODE JENIS NILAI": "kode_jenis_nilai",
    "KODE KANTOR MUAT": "kode_kantor_muat",
    "NOMOR DAFTAR": "nomor_daftar",
    "TANGGAL DAFTAR": "tanggal_daftar",
    "KODE ASAL BARANG FTZ": "kode_barang_asal_ftz",
    "KODE TUJUAN PENGELUARAN": "kode_tujuan_pengeluaran",
    "PPN PAJAK": "ppn_pajak",
    "PPNBM PAJAK": "ppnbm_pajak",
    "TARIF PPN PAJAK": "tarif_ppn_pajak",
    "TARIF PPNBM PAJAK": "tarif_ppnbm_pajak",
    "BARANG TIDAK BERWUJUD": "barang_tidak_berwujud",
}

# Date fields that need special handling
DATE_FIELDS = [
    "tanggal_bc11", "tanggal_berangkat", "tanggal_ekspor", "tanggal_masuk",
    "tanggal_muat", "tanggal_tiba", "tanggal_periksa", "tanggal_stuffing",
    "tanggal_pernyataan", "tanggal_bukti_bayar", "tanggal_daftar"
]

# Numeric fields
NUMERIC_FIELDS = [
    "jumlah_tanda_pengaman", "asuransi", "nilai_barang", "nilai_incoterm",
    "nilai_maklon", "freight", "fob", "biaya_tambahan", "biaya_pengurang",
    "vd", "cif", "harga_penyerahan", "ndpbm", "total_dana_sawit",
    "dasar_pengenaan_pajak", "nilai_jasa", "uang_muka", "bruto", "netto", "volume",
    "ppn_pajak", "ppnbm_pajak", "tarif_ppn_pajak", "tarif_ppnbm_pajak"
]
