# generated by datamodel-codegen:
#   filename:  bc27-out.json
#   timestamp: 2024-01-25T07:54:43+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel


class BahanBakuTarifItem(BaseModel):
    seriBahanBaku: int
    kodeJenisPungutan: str
    kodeAsalBahanBaku: str
    kodeFasilitasTarif: str
    nilaiBayar: float
    nilaiFasilitas: float
    nilaiSudahDilunasi: float
    tarif: float
    tarifFasilitas: float
    jumlahSatuan: float
    kodeJenisTarif: str
    seriBarang: int


class BahanBakuItem(BaseModel):
    cif: float
    cifRupiah: float
    hargaPenyerahan: float
    hargaPerolehan: float
    jumlahSatuan: float
    kodeAsalBahanBaku: str
    kodeBarang: str
    kodeDokAsal: str
    kodeKantor: str
    kodeSatuanBarang: str
    merkBarang: str
    ndpbm: float
    netto: float
    nilaiJasa: float
    posTarif: str
    nomorAjuDokAsal: str
    nomorDaftarDokAsal: str
    seriBahanBaku: int
    seriBarang: int
    seriBarangDokAsal: int
    seriIjin: int
    spesifikasiLainBarang: str
    tanggalDaftarDokAsal: str
    tipeBarang: str
    ukuranBarang: str
    uraianBarang: str
    bahanBakuTarif: List[BahanBakuTarifItem]


class BarangItem(BaseModel):
    cif: float
    cifRupiah: float
    hargaEkspor: float
    hargaPenyerahan: float
    hargaPerolehan: float
    isiPerKemasan: int
    jumlahSatuan: float
    kodeBarang: str
    kodeSatuanBarang: str
    merk: str
    ndpbm: float
    netto: float
    nilaiBarang: float
    nilaiJasa: float
    posTarif: str
    seriBarang: str
    spesifikasiLain: str
    tipe: str
    uangMuka: float
    ukuran: str
    uraian: str
    bahanBaku: List[BahanBakuItem]


class Dokuman(BaseModel):
    idDokumen: str
    kodeDokumen: str
    nomorDokumen: str
    seriDokumen: int
    tanggalDokumen: str


class Entita(BaseModel):
    alamatEntitas: str
    kodeEntitas: str
    kodeJenisIdentitas: str
    namaEntitas: str
    kodeJenisApi: str
    kodeStatus: str
    nomorIdentitas: str
    nomorIjinEntitas: str
    seriEntitas: int
    tanggalIjinEntitas: str
    nibEntitas: str


class KemasanItem(BaseModel):
    jumlahKemasan: int
    kodeJenisKemasan: str
    merkKemasan: str
    seriKemasan: int


class PengangkutItem(BaseModel):
    namaPengangkut: str
    nomorPengangkut: str
    seriPengangkut: str


class PungutanItem(BaseModel):
    kodeFasilitasTarif: str
    kodeJenisPungutan: str
    nilaiPungutan: float
    idPungutan: str


class Model(BaseModel):
    asalData: str
    asuransi: float
    biayaTambahan: float
    biayaPengurang: float
    bruto: float
    cif: float
    disclaimer: str
    freight: float
    hargaPenyerahan: float
    jabatanTtd: str
    jumlahKontainer: int
    kodeDokumen: str
    kodeJenisTpb: str
    kodeKantor: str
    kodeKantorTujuan: str
    kodeTps: str
    kodeTujuanPengiriman: str
    kodeTujuanTpb: str
    kodeValuta: str
    kotaTtd: str
    namaTtd: str
    ndpbm: float
    netto: float
    nik: str
    nilaiBarang: float
    nilaiJasa: float
    nomorAju: str
    seri: int
    tanggalAju: str
    tanggalTtd: str
    barang: List[BarangItem]
    dokumen: List[Dokuman]
    entitas: List[Entita]
    kemasan: List[KemasanItem]
    kontainer: List
    pengangkut: List[PengangkutItem]
    pungutan: List[PungutanItem]
    uangMuka: float
    vd: float
