# generated by datamodel-codegen:
#   filename:  bc20-out-pib.json
#   timestamp: 2024-01-30T10:18:29+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel


class BarangDokuman(BaseModel):
    seriDokumen: str


class BarangTarifItem(BaseModel):
    jumlahSatuan: int
    kodeFasilitasTarif: str
    kodeJenisPungutan: str
    kodeJenisTarif: str
    nilaiBayar: float
    nilaiFasilitas: float
    seriBarang: int
    tarif: float
    tarifFasilitas: Optional[float] = None
    jumlahKemasan: Optional[int] = None
    kodeKemasan: Optional[str] = None
    kodeKomoditiCukai: Optional[str] = None
    kodeSatuanBarang: Optional[str] = None
    kodeSubKomoditiCukai: Optional[str] = None
    nilaiSudahDilunasi: Optional[int] = None


class BarangVdItem(BaseModel):
    kodeJenisVd: str
    nilaiBarangVd: int


class BarangItem(BaseModel):
    asuransi: float
    bruto: int
    cif: float
    cifRupiah: float
    diskon: float
    fob: int
    freight: int
    hargaEkspor: int
    hargaPatokan: int
    hargaPenyerahan: int
    hargaPerolehan: int
    hargaSatuan: float
    hjeCukai: int
    isiPerKemasan: int
    jumlahBahanBaku: int
    jumlahDilekatkan: int
    jumlahKemasan: int
    jumlahPitaCukai: int
    jumlahRealisasi: int
    jumlahSatuan: int
    kapasitasSilinder: int
    kodeJenisKemasan: str
    kodeKondisiBarang: str
    kodeNegaraAsal: str
    kodeSatuanBarang: str
    merk: str
    ndpbm: float
    netto: float
    nilaiBarang: int
    nilaiDanaSawit: int
    nilaiDevisa: int
    nilaiTambah: int
    pernyataanLartas: str
    persentaseImpor: int
    posTarif: str
    saldoAkhir: float
    saldoAwal: float
    seriBarang: int
    seriBarangDokAsal: int
    seriIjin: int
    tahunPembuatan: int
    tarifCukai: int
    tipe: str
    uraian: str
    volume: int
    barangDokumen: List[BarangDokuman]
    barangTarif: List[BarangTarifItem]
    barangVd: List[BarangVdItem]
    barangSpekKhusus: List
    barangPemilik: List


class Entita(BaseModel):
    alamatEntitas: str
    kodeEntitas: str
    kodeJenisApi: Optional[str] = None
    kodeJenisIdentitas: Optional[str] = None
    kodeStatus: Optional[str] = None
    namaEntitas: str
    nibEntitas: Optional[str] = None
    nomorIdentitas: Optional[str] = None
    seriEntitas: int
    kodeNegara: Optional[str] = None


class KemasanItem(BaseModel):
    jumlahKemasan: int
    kodeJenisKemasan: str
    merkKemasan: str
    seriKemasan: int


class KontainerItem(BaseModel):
    kodeJenisKontainer: str
    kodeTipeKontainer: str
    kodeUkuranKontainer: str
    nomorKontainer: str
    seriKontainer: int


class Dokuman(BaseModel):
    idDokumen: str
    kodeDokumen: str
    kodeFasilitas: str
    nomorDokumen: str
    seriDokumen: int
    tanggalDokumen: str
    namaFasilitas: Optional[str] = None


class PengangkutItem(BaseModel):
    kodeBendera: str
    namaPengangkut: str
    nomorPengangkut: str
    kodeCaraAngkut: str
    seriPengangkut: int


class Model(BaseModel):
    asalData: str
    asuransi: int
    biayaPengurang: int
    biayaTambahan: int
    bruto: float
    cif: float
    disclaimer: str
    flagVd: str
    fob: int
    freight: int
    hargaPenyerahan: int
    idPengguna: str
    jabatanTtd: str
    jumlahKontainer: int
    jumlahTandaPengaman: int
    kodeAsuransi: str
    kodeCaraBayar: str
    kodeDokumen: str
    kodeIncoterm: str
    kodeJenisImpor: str
    kodeJenisNilai: str
    kodeJenisProsedur: str
    kodeKantor: str
    kodePelMuat: str
    kodePelTransit: str
    kodePelTujuan: str
    kodeTps: str
    kodeTutupPu: str
    kodeValuta: str
    kotaTtd: str
    namaTtd: str
    ndpbm: float
    netto: float
    nilaiBarang: int
    nilaiIncoterm: int
    nilaiMaklon: int
    nomorAju: str
    nomorBc11: str
    posBc11: str
    seri: int
    subPosBc11: str
    tanggalAju: str
    tanggalBc11: str
    tanggalTiba: str
    tanggalTtd: str
    totalDanaSawit: int
    volume: int
    vd: int
    barang: List[BarangItem]
    entitas: List[Entita]
    kemasan: List[KemasanItem]
    kontainer: List[KontainerItem]
    dokumen: List[Dokuman]
    pengangkut: List[PengangkutItem]
