# generated by datamodel-codegen:
#   filename:  bc41-out.json
#   timestamp: 2024-01-30T06:59:17+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel


class BahanBakuItem(BaseModel):
    cif: int
    cifRupiah: int
    hargaPenyerahan: float
    hargaPerolehan: int
    jumlahSatuan: int
    kodeAsalBahanBaku: str
    kodeBarang: str
    kodeDokAsal: str
    kodeDokumen: str
    kodeKantor: str
    kodeSatuanBarang: str
    merkBarang: str
    ndpbm: int
    netto: int
    nilaiJasa: int
    nomorAjuDokAsal: str
    nomorDaftarDokAsal: str
    posTarif: str
    seriBahanBaku: int
    seriBarang: int
    seriBarangDokAsal: int
    seriIjin: int
    spesifikasiLainBarang: str
    tanggalDaftarDokAsal: str
    tipeBarang: str
    ukuranBarang: str
    uraianBarang: str


class BarangItem(BaseModel):
    bahanBaku: List[BahanBakuItem]
    cif: int
    cifRupiah: int
    hargaEkspor: int
    hargaPenyerahan: float
    hargaPerolehan: int
    isiPerKemasan: int
    jumlahKemasan: int
    jumlahSatuan: int
    kodeAsalBahanBaku: str
    kodeBarang: str
    kodeDokumen: str
    kodeJenisKemasan: str
    kodeSatuanBarang: str
    merk: str
    ndpbm: int
    netto: int
    nilaiBarang: int
    nilaiJasa: int
    posTarif: str
    seriBarang: int
    spesifikasiLain: str
    tipe: str
    uangMuka: int
    ukuran: str
    uraian: str
    volume: int


class Dokuman(BaseModel):
    idDokumen: str
    kodeDokumen: str
    nomorDokumen: str
    seriDokumen: int
    tanggalDokumen: str


class Entita(BaseModel):
    alamatEntitas: str
    kodeEntitas: str
    kodeJenisApi: str
    kodeJenisIdentitas: str
    kodeStatus: str
    namaEntitas: str
    nibEntitas: str
    nomorIdentitas: str
    nomorIjinEntitas: str
    seriEntitas: int
    tanggalIjinEntitas: str


class KemasanItem(BaseModel):
    jumlahKemasan: int
    kodeJenisKemasan: str
    merkKemasan: str
    seriKemasan: int


class PengangkutItem(BaseModel):
    namaPengangkut: str
    nomorPengangkut: str
    seriPengangkut: str


class Model(BaseModel):
    asalData: str
    asuransi: int
    barang: List[BarangItem]
    biayaPengurang: int
    biayaTambahan: int
    bruto: float
    cif: int
    dokumen: List[Dokuman]
    entitas: List[Entita]
    freight: int
    hargaPenyerahan: float
    jabatanTtd: str
    jumlahKontainer: int
    kemasan: List[KemasanItem]
    kodeDokumen: str
    kodeJenisEkspor: str
    kodeJenisImpor: str
    kodeJenisTpb: str
    kodeKantor: str
    kodeLokasiBayar: str
    kodePembayar: str
    kodeTujuanPengiriman: str
    kontainer: List
    kotaTtd: str
    namaTtd: str
    ndpbm: int
    netto: int
    nik: str
    nilaiBarang: int
    nomorAju: str
    pengangkut: List[PengangkutItem]
    seri: int
    tanggalAju: str
    tanggalTtd: str
    uangMuka: int
    userPortal: str
    vd: int
    volume: int
