# generated by datamodel-codegen:
#   filename:  bc25-out.json
#   timestamp: 2024-01-25T03:04:18+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel


class BahanBakuTarifItem(BaseModel):
    jumlahSatuan: int
    kodeFasilitasTarif: str
    kodeJenisPungutan: str
    kodeJenisTarif: str
    nilaiBayar: int
    nilaiFasilitas: float
    nilaiSudahDilunasi: int
    seriBahanBaku: int
    tarif: float
    tarifFasilitas: float


class BahanBakuItem(BaseModel):
    cif: float
    cifRupiah: float
    hargaPenyerahan: float
    jumlahSatuan: float
    kodeAsalBahanBaku: str
    kodeBarang: str
    kodeDokAsal: str
    kodeKantor: str
    kodeSatuanBarang: str
    merkBarang: str
    ndpbm: float
    nomorAjuDokAsal: str
    nomorDaftarDokAsal: str
    posTarif: str
    seriBahanBaku: int
    seriBarang: int
    seriBarangDokAsal: int
    seriIjin: int
    spesifikasiLainBarang: str
    tanggalDaftarDokAsal: str
    tipeBarang: str
    bahanBakuTarif: List[BahanBakuTarifItem]
    ukuranBarang: str
    uraianBarang: str


class BarangTarifItem(BaseModel):
    seriBarang: int
    kodeJenisTarif: str
    jumlahSatuan: int
    kodeFasilitasTarif: str
    kodeSatuanBarang: str
    kodeJenisPungutan: str
    nilaiBayar: float
    nilaiFasilitas: float
    nilaiSudahDilunasi: int
    tarif: float
    tarifFasilitas: float


class BarangItem(BaseModel):
    cif: float
    cifRupiah: float
    diskon: int
    fob: int
    freight: int
    hargaEkspor: int
    hargaPenyerahan: float
    hargaPerolehan: int
    isiPerKemasan: int
    jumlahKemasan: int
    jumlahSatuan: float
    kodeBarang: str
    kodeDokAsal: str
    kodeGunaBarang: str
    kodeJenisKemasan: str
    kodeKategoriBarang: str
    kodeKondisiBarang: str
    kodePerhitungan: str
    kodeSatuanBarang: str
    merk: str
    ndpbm: int
    netto: float
    nilaiBarang: int
    posTarif: str
    seriBarang: int
    spesifikasiLain: str
    tipe: str
    ukuran: str
    uraian: str
    bahanBaku: List[BahanBakuItem]
    barangDokumen: List
    barangTarif: List[BarangTarifItem]


class Dokuman(BaseModel):
    idDokumen: str
    kodeDokumen: str
    nomorDokumen: str
    seriDokumen: int
    tanggalDokumen: str


class Entita(BaseModel):
    alamatEntitas: str
    kodeEntitas: str
    kodeJenisApi: Optional[str] = None
    kodeJenisIdentitas: str
    kodeStatus: str
    namaEntitas: str
    nibEntitas: Optional[str] = None
    nomorIdentitas: str
    nomorIjinEntitas: Optional[str] = None
    seriEntitas: int
    tanggalIjinEntitas: Optional[str] = None
    niperEntitas: Optional[str] = None


class KemasanItem(BaseModel):
    kodeJenisKemasan: str
    merkKemasan: str
    seriKemasan: int
    jumlahKemasan: int


class PengangkutItem(BaseModel):
    kodeCaraAngkut: str
    namaPengangkut: str
    nomorPengangkut: str
    seriPengangkut: int


class Model(BaseModel):
    asalData: str
    barang: List[BarangItem]
    bruto: float
    cif: float
    disclaimer: str
    dokumen: List[Dokuman]
    entitas: List[Entita]
    hargaPenyerahan: float
    idPengguna: str
    jabatanTtd: str
    jumlahKontainer: int
    kemasan: List[KemasanItem]
    kodeCaraBayar: str
    kodeDokumen: str
    kodeJenisTpb: str
    kodeKantor: str
    kodeLokasiBayar: str
    kodeTujuanPengiriman: str
    kodeValuta: str
    kontainer: List
    kotaTtd: str
    namaTtd: str
    ndpbm: float
    netto: float
    nomorAju: str
    pengangkut: List[PengangkutItem]
    seri: int
    tanggalAju: str
    tanggalTtd: str
    volume: int
