# generated by datamodel-codegen:
#   filename:  bc23-out.json
#   timestamp: 2024-01-25T02:13:40+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel


class BarangTarifItem(BaseModel):
    kodeJenisTarif: str
    jumlahSatuan: int
    kodeFasilitasTarif: str
    kodeSatuanBarang: str
    kodeJenisPungutan: str
    nilaiBayar: int
    nilaiFasilitas: float
    nilaiSudahDilunasi: int
    seriBarang: int
    tarif: float
    tarifFasilitas: int


class BarangDokuman(BaseModel):
    seriDokumen: str


class BarangItem(BaseModel):
    idBarang: str
    asuransi: int
    cif: int
    diskon: int
    fob: int
    freight: int
    hargaEkspor: int
    hargaPenyerahan: int
    hargaSatuan: float
    isiPerKemasan: int
    jumlahKemasan: int
    jumlahSatuan: int
    kodeBarang: str
    kodeDokumen: str
    kodeKategoriBarang: str
    kodeJenisKemasan: str
    kodeNegaraAsal: str
    kodePerhitungan: str
    kodeSatuanBarang: str
    merk: str
    netto: int
    nilaiBarang: int
    nilaiTambah: int
    posTarif: str
    seriBarang: int
    spesifikasiLain: str
    tipe: str
    ukuran: str
    uraian: str
    ndpbm: int
    cifRupiah: int
    hargaPerolehan: int
    kodeAsalBahanBaku: str
    barangTarif: List[BarangTarifItem]
    barangDokumen: List[BarangDokuman]


class Entita(BaseModel):
    alamatEntitas: str
    kodeEntitas: str
    kodeJenisIdentitas: str
    namaEntitas: str
    nibEntitas: Optional[str] = None
    nomorIdentitas: str
    nomorIjinEntitas: str
    tanggalIjinEntitas: str
    seriEntitas: int
    kodeJenisApi: Optional[str] = None
    kodeStatus: Optional[str] = None


class KemasanItem(BaseModel):
    jumlahKemasan: int
    kodeJenisKemasan: str
    seriKemasan: int
    merkKemasan: str


class KontainerItem(BaseModel):
    kodeTipeKontainer: str
    kodeUkuranKontainer: str
    nomorKontainer: str
    seriKontainer: int
    kodeJenisKontainer: str


class Dokuman(BaseModel):
    idDokumen: str
    kodeDokumen: str
    nomorDokumen: str
    seriDokumen: int
    tanggalDokumen: str


class PengangkutItem(BaseModel):
    kodeBendera: str
    namaPengangkut: str
    nomorPengangkut: str
    kodeCaraAngkut: str
    seriPengangkut: int


class Model(BaseModel):
    asalData: str
    asuransi: float
    bruto: int
    cif: int
    fob: int
    freight: int
    hargaPenyerahan: int
    jabatanTtd: str
    jumlahKontainer: int
    kodeAsuransi: str
    kodeDokumen: str
    kodeIncoterm: str
    kodeKantor: str
    kodeKantorBongkar: str
    kodePelBongkar: str
    kodePelMuat: str
    kodePelTransit: str
    kodeTps: str
    kodeTujuanTpb: str
    kodeTutupPu: str
    kodeValuta: str
    kotaTtd: str
    namaTtd: str
    ndpbm: int
    netto: int
    nik: str
    nilaiBarang: int
    nomorAju: str
    nomorBc11: str
    posBc11: str
    seri: int
    subposBc11: str
    tanggalBc11: str
    tanggalTiba: str
    tanggalTtd: str
    biayaTambahan: int
    biayaPengurang: int
    kodeKenaPajak: str
    barang: List[BarangItem]
    entitas: List[Entita]
    kemasan: List[KemasanItem]
    kontainer: List[KontainerItem]
    dokumen: List[Dokuman]
    pengangkut: List[PengangkutItem]
